---
- name: Full setup (minimal + storage + graphical apps)
  hosts: all
  roles:
    - name: zsh
    - name: git
      vars:
        git_name: "{{ secret_fullname }}"
        git_email: "{{ secret_email }}"
    - name: keypair
      vars:
        key_name: github
        key_host: github.com
        public: "{{ secret_git_key_public }}"
        private: "{{ secret_git_key_private }}"
    - name: nix
    - name: home-manager
      vars:
        editor: vim
        git_name: "{{ secret_fullname }}"
        git_email: "{{ secret_email }}"
    - name: storage-personal
      vars:
        mounts:
          - src: UUID=7C4C7B584C7B0BE0
            path: /media/data1
            fstype: ntfs
            opts: defaults,nofail,uid=1000,gid=1000,rw,user,exec,umask=000
            steam_libraries:
              - Games/Steam
    - name: applications
    - name: flatpaks
