---
- name: Minimal setup
  hosts: all
  roles:
    - zsh
    - name: git
      vars:
        git_name: "{{ secret_fullname }}"
        git_email: "{{ secret_email }}"
    - name: keypair
      vars:
        key_name: github
        key_host: github.com
        public: "{{ secret_git_key_public }}"
        private: "{{ secret_git_key_private }}"
    - nix
    - name: home-manager
      vars:
        editor: vim
        git_name: "{{ secret_fullname }}"
        git_email: "{{ secret_email }}"
