editor: vim
user_home: "/home/{{ secret_username }}"
mounts:
  - src: UUID=7C4C7B584C7B0BE0
    path: /media/data1
    fstype: ntfs
    opts: defaults,nofail,uid=1000,gid=1000,rw,user,exec,umask=000
    steam_libraries:
      - Games/Steam
applications_system:
  - curl
  - git
  - htop
  - jq
  - neovim
  - rsync
  - vim
  - wget
  - yakuake 
  - zsh
flatpaks_user:
  - com.bitwarden.desktop
  - com.google.Chrome
  - com.spotify.Client
  - org.gnome.World.PikaBackup