---
- name: Make sure ZSH is installed
  become: true
  ansible.builtin.package:
    name: zsh
    state: present
- name: Check if Oh My Zsh is installed
  ansible.builtin.shell:
    cmd: >-
      [ -d /home/{{ secret_username }}/.oh-my-zsh ] && echo yes || echo no
  register: installed
- name: Install Oh My Zsh
  when: installed.stdout == 'no'
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
- name: Set default shell
  become: true
  ansible.builtin.command:
    cmd: chsh --shell /bin/zsh {{ secret_username }}