name: Build and deploy to Home Manager repo

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Home Manager config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: thisRepo
          submodules: recursive
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Setup nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Write encrypted Ansible vault
        working-directory: thisRepo
        run: echo '${{ secrets.ANSIBLE_VAULT }}' > group_vars/all/vault.yml
      - name: Write vault password
        working-directory: thisRepo
        run: echo '${{ secrets.ANSIBLE_VAULT_PASSWORD }}' > .vault-password
      - name: Generate Home Manager configuration
        working-directory: thisRepo
        run: >
            nix-shell --run "
            ansible-playbook main.yml
            --inventory inventory/localhost.yml
            --tags home-manager
            --extra-vars home_manager_root='${{ github.workspace }}/build'
            "
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
  deploy:
    needs: build
    name: Deploy generated configuration
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout destination repo
        uses: actions/checkout@v3
        with:
          repository: lpchaim/home-manager
          ref: ${{ github.head_ref }}
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Commit new configuration
        id: commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit --message "chore: Update Home Manager"
      - name: Push changes
        if: steps.commit.conclusion == 'success'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: lpchaim/home-manager
          branch: ${{ github.head_ref }}
          force: true
